name: Build Instagram Scraper App (macOS)

on:
  push:
    branches: [ main ]  # Triggers when you push to main branch

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install py2app

      - name: Build .app using py2app
        run: python setup.py py2app

      - name: Create .dmg
        run: |
          hdiutil create -volname InstagramScraper \
            -srcfolder dist/Instagram\ Scraper.app \
            -ov -format UDZO InstagramScraper.dmg

      - name: Upload .dmg as artifact
        uses: actions/upload-artifact@v3
        with:
          name: InstagramScraper
          path: InstagramScraper.dmg
